### PR TITLE
Fix root node deprecation in symfony/config > 4.1

### PR DESCRIPTION
**Pull request by karser**
See: https://github.com/symfony/symfony/blob/master/UPGRADE-4.2.md#config

### CODE REVIEW

**Comment by Nyholm** [comment]
This is awesome. Thanks!

**Comment by nmeirik** [comment]
@Nyholm Is it possible to have a release which includes this fix?

**Comment by Nyholm** [comment]
Sure. Can you just update the change log?

**Comment by nmeirik** [comment]
Change log updated: https://github.com/backup-manager/symfony/pull/55

**Pull request merged**
