### PR TITLE
Add support for Symfony 6

### LINKED ISSUE #86: Support Symfony 6
The bundle does not support symfony 6.

### PR DESCRIPTION
**Pull request by trsteel88**
Closes #86

### CODE REVIEW

**Comment by trsteel88** [comment]
@Nyholm is the backup manager still maintained?

This PR would also require the following PR's to be merged too:

- [x] https://github.com/backup-manager/backup-manager/pull/178
- [x] https://github.com/backup-manager/backup-manager/pull/176

**Comment by Nyholm** [comment]
Hey. 

Yes, I'll look at it time to time (or when I get pinged). Would you be interested to help out?

**Review by Nyholm — APPROVED** [review]

**Comment by trsteel88** [comment]
Thanks @Nyholm. Happy to help where I can.

**Comment by svenpet90** [comment]
Is there a loose timeframe for when a new version with these changes will be released?! :) 

thanks so much in advance!

**Pull request merged**
