### PR TITLE
Error message explanation

### PR DESCRIPTION
**Pull request by ousmaneNdiaye**
Either I  don't understand the meaning...

### CODE REVIEW

**Comment by wartab** [comment]
Yes, you don't understand.

**Comment by ShawnMcCool** [comment]
This is a chance to correct the opportunity for misunderstanding by proposing a more clear explanation.

**Comment by Nyholm** [comment]
Thank you @ShawnMcCool. That sounds like a great idea. 

@ousmaneNdiaye could you update the PR?

**Comment by Nyholm** [comment]
Thank you

**Pull request merged**
