### PR TITLE
update backup command help info.

### PR DESCRIPTION
**Pull request by lcp0578**
When i call `backup-manager:backup` in another command. destinations arg  confuses me.

### CODE REVIEW

**Comment by Nyholm** [comment]
Could you please elaborate?

**Comment by Nyholm** [comment]
Im still not sure what you mean. Are you saying that when you write your own command that invokes the `backup-manager:backup`, then you are confused by the output? That is why you would like to have: 

```php
$output->writeln([
            'end backup database',
            '--------------'
        ]);
```

If so, you should rather update your command to print whatever you want.

**Comment by lcp0578** [comment]
Oh,

```
$args = [
            'command' => 'backup-manager:backup',
            'database' => 'production',
            **'destinations' => ['local'], //THIS IS ARRAY!!!, not 'destinations' => 'local'**,
            '-c' => 'gzip',
            '--filename' => $fileName
        ];
```

**Comment by Nyholm** [comment]
Please use words when describing what you want. I don’t want to guess

**Comment by lcp0578** [comment]
I'm sorry,  when i call the command the args should be 'destinations' => ['local'], not 'destinations' => 'local', it is cost a lot time for me.

**Comment by lcp0578** [comment]
my PR:

` ->addArgument('destinations', InputArgument::IS_ARRAY, 'What storages do you want to upload the backup to? Must be array.')` 

It is defined `IS_ARRAY`, so i think should update `command --help` info to warning it is must be array for the argument "destinations".

**Comment by Nyholm** [comment]
Doesn't `InputArgument::IS_ARRAY` already specify that?

**Comment by lcp0578** [comment]
Yes, but I want to enrich the command help information

**Pull request merged**
