### PR TITLE
Upgraded backup-manager dependency

### LINKED ISSUE #65: SYMFONY5 SUPPORT FOR SYMFONY/PROCESS
Hi

When I tried to update to 2.3.* I got this error

 Problem 1
    - backup-manager/backup-manager 1.4.1 requires symfony/process ^2.1 || ^3.0 || ^4 -> no matching package found.
    - backup-manager/backup-manager 1.4 requires symfony/process ^2.1 || ^3.0 || ^4.0 -> no matching package found.
    - backup-manager/backup-manager 1.3.0 requires symfony/process ^2.1 || ^3.0 || ^4.0 -> no matching package found.
    - backup-manager/symfony 2.3.0 requires backup-manager/backup-manager ^1.3 -> satisfiable by backup-manager/backup-manager[1.3.0, 1.4, 1.4.1].
    - Installation request for backup-manager/symfony 2.3.* -> satisfiable by backup-manager/symfony[2.3.0].

But I have the symfony/process in 5.0.3 version. Any idea?

### PR DESCRIPTION
**Pull request by mscharl**
I saw a lot of people mentioned that the dependency needs to be updated for Symfony 5. But nobody create a pull request. So here it is.

fixes #65

### CODE REVIEW

**Comment by ShawnMcCool** [comment]
Hi there, thanks for taking the initiative. Can you weigh in on why the build is failing?

https://travis-ci.org/github/backup-manager/symfony/jobs/683321822

**Comment by mscharl** [comment]
I had to remove PHP 7.2 support because [backup-manager/backup-manager](https://github.com/backup-manager/backup-manager) does not support it any more.

I have now adjusted the test configuration accordingly.

Should I update the changes file or will this be done when the new version tag is created?

**Comment by ShawnMcCool** [comment]
I'll start by merging in the changes.

Thank you very much.

Could you update the changelog and test that dev-master is indeed working. If it is then I'll tag it as a new release.

**Comment by mscharl** [comment]
I installed `dev-master` and tested it locally and on one of our staging servers.

Changes are done in #68

**Comment by ShawnMcCool** [comment]
@mscharl thanks for your work

due to breaking backwards compatibility I have tagged the current version at 3.0.0

**Pull request merged**
